### ISSUE TITLE
Bug: Addition of two QuantumFloats that are multiplied by classical numbers

### ISSUE THREAD

**Issue by renezander90** [eclipse-qrisp/Qrisp#104]
Consider the following example:
```
from qrisp import *
import numpy as np

qf1 = QuantumFloat(10)
qf1[:] = 3

qf2 = QuantumFloat(10)
qf2[:] = 1

res1 = 3*qf1
res2 = 4*qf2
res = res1 + res2
print(res)
```
>Yields: {45: 1.0} 

It should be 3 * 3 + 4 * 1 = 13.

Another example:
```
from qrisp import *
import numpy as np

qf1 = QuantumFloat(10)
qf1[:] = 3

qf2 = QuantumFloat(10)
qf2[:] = 1

res1 = qf1*3
res2 = qf2*2
res = res1 + res2
print(res)
```
> Yields: {27: 0.50073, 2075: 0.49927}

**Comment by renezander90** [comment]
Also note that

```
from qrisp import *
import numpy as np

s = QuantumArray(qtype = QuantumFloat(6), shape = (2,1))
s[:] = np.array([[3],[1]])

A = np.array([[3,4]], dtype=int)
res = A @ s

print(res)
```

sometimes yields: 
> {OutcomeArray([[45]]): 0.76726, OutcomeArray([[13]]): 0.23274}

and sometimes (rarely) yields the correct result: 
> {OutcomeArray([[13]]): 1.0}

**Comment by positr0nium** [comment]
Fixed in https://github.com/eclipse-qrisp/Qrisp/commit/bcf458f5da80e025055fdd02384661bdde474334
