### ISSUE TITLE
Bug report: ConditionEnvironment in python 3.12

### ISSUE THREAD

**Issue by renezander90** [eclipse-qrisp/Qrisp#55]
The following code, when executed in a python environment with python=**3.12** and the Qrisp version from the main branch on GitHub,
```
from qrisp import QuantumChar, QuantumFloat, h, multi_measurement

q_ch = QuantumChar()
qf = QuantumFloat(3, signed = True)

h(q_ch[0])

with q_ch == "a":
    qf += 2
```
produces a bug: 
> AttributeError: 'NoneType' object has no attribute 'deallocated_qubits'

A similar bug occurs for the ControlEnvironment in this setting.

**Comment by positr0nium** [comment]
Fixed by the amazing @Nik-Stein in https://github.com/eclipse-qrisp/Qrisp/pull/34
