### ISSUE TITLE
Bug: Compilationaccelaration on QuantumBools

### ISSUE THREAD

**Issue by Nik-SteinFraunh** [eclipse-qrisp/Qrisp#67]
1. case: Occurs when Compilationaccelaration acts on QuantumBools/ConditionEnvironments, see code and attached screenshot. Work-Around in this case: have the cx in the less_than function act on res[0] instead of res 
2. case: Addtionally when derefferencing QuantumArrays with quantum floats another error occurs, see 2nd code block and second screenshot
 
1 . case:
```
        from qrisp import quantum_condition, cx, QuantumBool, QuantumArray, QuantumFloat, h, QuantumVariable
        qarray_size = 8
        nq = 4
        qtype = QuantumFloat(nq, -2)
        a = 1.5
        b = 0.25
        c = a + b
        d = a + c
        q_array = QuantumArray(qtype)
        q_array[:] = [a,b,c,d]
        
        @quantum_condition
        def less_than(qf_0, qf_1):
            temp_qf = qf_0 - qf_1
            res = QuantumBool()
            cx(temp_qf.sign(), res)
            return res
        
        ac = QuantumVariable(1)    
        entry = q_array[3]
        pick = q_array[1]
        with less_than(entry, pick):
            h(ac)
```

![Bild](https://github.com/user-attachments/assets/5632e69a-2621-45cf-8a9a-6bad3c39a0d3)

2. case: 

```
    ac = QuantumVariable(1)    
    inx = QuantumFloat(2, -2)
    entry = qf_array[4]
    pick = qf_array[inx]

    with less_than(entry, pick):
        #rz(np.pi/8, qb)
        h(ac)
```
![bug_report](https://github.com/user-attachments/assets/13de72dd-077d-4f37-a9d7-bfc0a3a19d89)

**Comment by positr0nium** [comment]
The first case is fixed with https://github.com/eclipse-qrisp/Qrisp/commit/4b480d036ab45c3c5e9e54050d73ead30320bf86
For the second case the syntax is wrong. What you want is achieved with:

```
with q_array[inx] as pick:
    with less_than(entry, pick):
        #rz(np.pi/8, qb)
        h(ac)
```
