### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by JRGit4UE** [eclipse-qrisp/Qrisp#80]
As **Qrisp** has updated the underlying **Qiskit** version towards *1.1.1*, which breaks with *0.46.0*, it might be helpful to reflect the progress in documentation and test codes of Qrisp as well.
Main change affects how to employ `Air.get_backend('qasm_simulator')`, so to switch from
```python
from qiskit import Aer  # does not work in 1.1.1
qiskit_backend = Aer.get_backend('qasm_simulator')
```
to 
```python
import qiskit_aer as Aer
qiskit_backend = Aer.AerSimulator()
```
which means
```
search
from qiskit import Aer
replace with
import qiskit_aer as Aer

search
Aer.get_backend('qasm_simulator')
Aer.get_backend("qasm_simulator")

replace with
Aer.AerSimulator()
 
```
Affected 9 files are
![qrisp-affected-files-for-update](https://github.com/user-attachments/assets/70f0317f-72d8-48dc-ab64-e8d86d252123)

I'm not deeply in the Qrisp framework so that a PR would make sense...

**Comment by renezander90** [comment]
Fixed with Qrisp 0.5
